name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest
    container: rust:latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: cargo build --all --verbose